//  import icons
import 'bootstrap-icons/font/bootstrap-icons.css';

// import bootstrap
import 'bootstrap/dist/css/bootstrap.css';

//  animation on scroll

import 'aos/dist/aos.css';

import type { Metadata } from "next";
import { EB_Garamond } from "next/font/google";



// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
import Header from '@/components/Header';
import './variables.css'; 
import "./globals.css";
const  ebGaramond= EB_Garamond({subsets: ['latin']});

export const metadata: Metadata = {
  title: "digital news app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ebGaramond.className}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
